---
- hosts: all
  user: maha
  become: yes
  tasks: 
        - name: install apcahe in ubuntu
          command: apt-get -y install apache
          when: ansible_os_family == "Debian"
        - name: install httpd for redhat family
          command: yum -y install httpd
          when: ansible_os_family == "redhat"
